Redid zipping process
Change-Id: Ic410c95e3972c2e955ad7edd26035494c3a6b758

diff --git a/tools/squisher b/tools/squisher
--- a/tools/squisher
+++ b/tools/squisher
@@ -3,6 +3,7 @@
 # Squish a CM otapackage for distribution
 # cyanogen
 #
+. $ANDROID_BUILD_TOP/vendor/illusion/tools/functions
 
 OUT_TARGET_HOST=`uname -a | grep Darwin`
 if [ -z "$OUT_TARGET_HOST" ]
@@ -19,38 +20,24 @@ else
 fi
 
 if [ -z "$OUT" -o ! -d "$OUT" ]; then
-    echo "ERROR: $0 only works with a full build environment. $OUT should exist."
-    exit 1
-fi
-
-if [ "$TARGET_BUILD_TYPE" = "debug" ]; then
-    OTAPACKAGE=$OUT/${TARGET_PRODUCT}_debug-ota-$TARGET_BUILD_VARIANT.$USER.zip
-elif [ "$TARGET_BUILD_VARIANT" = "userdebug" ]; then
-    OTAPACKAGE=$OUT/$TARGET_PRODUCT-ota-eng.$USER.zip
-elif [ "$TARGET_BUILD_VARIANT" = "user" ]; then
-    OTAPACKAGE=$OUT/$TARGET_PRODUCT-ota-eng.$USER.zip
-else
-    OTAPACKAGE=$OUT/$TARGET_PRODUCT-ota-$TARGET_BUILD_VARIANT.$USER.zip
-fi
-if [ ! -f "$OTAPACKAGE" ]; then
-    echo "$OTAPACKAGE doesn't exist!";
-    exit 1
+	echo $CL_RED"ERROR: $0 only works with a full build environment. $OUT should exist."$CL_RST
+	exit 1
 fi
 
 OPTICHARGER=$ANDROID_BUILD_TOP/vendor/illusion/tools/opticharger
 QUIET=-q
 DELETE_BINS="applypatch applypatch_static check_prereq recovery updater"
+DELETE_LIBS="libc_malloc_debug_leak.so libc_malloc_debug_qemu.so"
+DELETE_FONTS="MTLmr3m.ttf"
 DELETE_MEDIA="*.qmg"
 DELETE_APKS="Launcher2.apk LiveWallpapers.apk VoiceDialer.apk SpeechRecorder.apk VideoEditor.apk Exchange2.apk HoloSpiralWallpaper.apk MagicSmokeWallpapers.apk NoiseField.apk Galaxy4.apk Calendar.apk OpenWnn.apk PinyinIME.apk QuickSearchBox.apk Email.apk"
 DELETE_GALLERY="Gallery2.apk"
-DELETE_FONTS="MTLmr3m.ttf"
 
 REPACK=$OUT/repack.d
-printf "Sanitizing environment..."
+printf "Sanitizing Environment..."
 rm -rf $REPACK
 mkdir -p $REPACK
 echo
-
 
 # Unpack the otapackage and opticharge all apks
 mkdir $REPACK/ota
@@ -86,15 +73,14 @@ $SED -i \
 	-e '/ro\.build\.type/s/eng/user/' \
 	$REPACK/ota/system/build.prop
 
-
 # Delete unnecessary binaries
 ( cd $REPACK/ota/system/bin; echo $DELETE_BINS | xargs rm -f; )
 
+# Delete unnecessary libraries
+( cd $REPACK/ota/system/lib; echo $DELETE_LIBS | xargs rm -f; )
+
 # Delete Offline charging mode files
 ( cd $REPACK/ota/system/media; echo $DELETE_MEDIA | xargs rm -f; )
-
-# Delete Home Apk
-( cd $REPACK/ota/system/app; echo $DELETE_APKS | xargs rm -f; )
 
 # No need for modem.bin
 rm -f $REPACK/ota/modem.bin
@@ -104,15 +90,6 @@ rm -rf $REPACK/ota/system/media/video
 
 # Delete Unnecessary Fonts
 ( cd $REPACK/ota/system/fonts; echo $DELETE_FONTS | xargs rm -f; )
-
-# Delete compiled fonts
-#rm -rf $REPACK/ota/system/fonts
-
-#make dir for fonts again
-#mkdir $REPACK/ota/system/fonts
-
-# Add precompiled fonts
-#mv -f $REPACK/ota/system/sfont/*.ttf $REPACK/ota/system/fonts/
 
 # No need for tts
 rm -rf $REPACK/ota/system/tts
@@ -131,13 +108,13 @@ rm -rf $REPACK/ota/system/etc/recovery-resource.dat
 # Fix LCD Density for illusion
 DEVICELCD=`sed -n -e'/ro\.sf\.lcd_density/s/^.*=//p' $OUT/system/build.prop`
 if [ "$DEVICELCD" = "240" ]; then
-   sed -i 's/ro.sf.lcd_density=240/ro.sf.lcd_density=182/g' $OUT/system/build.prop
+   sed -i 's/ro.sf.lcd_density=240/ro.sf.lcd_density=240/g' $OUT/system/build.prop
 elif [ "$DEVICELCD" = "320" ]; then
-    sed -i 's/ro.sf.lcd_density=320/ro.sf.lcd_density=245/g' $OUT/system/build.prop
+    sed -i 's/ro.sf.lcd_density=320/ro.sf.lcd_density=320/g' $OUT/system/build.prop
 elif [ "$DEVICELCD" = "480" ]; then
-    sed -i 's/ro.sf.lcd_density=480/ro.sf.lcd_density=361/g' $OUT/system/build.prop
+    sed -i 's/ro.sf.lcd_density=480/ro.sf.lcd_density=480/g' $OUT/system/build.prop
 elif [ "$DEVICELCD" = "213" ]; then
-    sed -i 's/ro.sf.lcd_density=213/ro.sf.lcd_density=182/g' $OUT/system/build.prop
+    sed -i 's/ro.sf.lcd_density=213/ro.sf.lcd_density=213/g' $OUT/system/build.prop
 fi
 
 # Fix LCD Density for GNote
@@ -153,23 +130,11 @@ elif [ "$DEVICEID" = "flo" ]; then
 fi
 cp -f $OUT/system/build.prop $REPACK/ota/system/build.prop
 
-# Delete Gallery2 for 5MP cameras
-CAMERARESOLUTION=`sed -n -e'/ro\.camera\.res/s/^.*=//p' $REPACK/ota/system/build.prop`
-#if [ "$CAMERARESOLUTION" = "5MP" ];then
-#   rm -f $REPACK/ota/system/app/Gallery2.apk
-#fi
-
-# Swap boot.img
-PREBUILTKERNEL=$OUT/system/illusionkernel/boot.img
-if [ -e "$PREBUILTKERNEL" ];then
-   rm -f $REPACK/ota/boot.img
-   mv -f $REPACK/ota/system/illusionkernel/boot.img $REPACK/ota/boot.img
-fi
-
 # Determine what to name the new signed package
-MODVERSION=`sed -n -e'/ro\.modversion/s/^.*=//p' $REPACK/ota/system/build.prop`
-OUTFILE=$OUT/$MODVERSION.zip
-echo MODVERSION: $MODVERSION
+MODVERSION=`sed -n -e'/ro\.illusion\.version/s/^.*=//p' $OUT/system/build.prop`
+TARGET_PRODUCT_FINAL=`echo $TARGET_PRODUCT | cut -d '_' -f2`
+echo $CL_CYN"MODVERSION: $MODVERSION"$CL_RST
+OUTFILE=$OUT/$MODVERSION-$TARGET_PRODUCT_FINAL.zip
 
 # Pack it up and sign
 printf "Zipping package..."
@@ -192,8 +157,8 @@ img=`basename $OUTFILE`
 cd `dirname $OUTFILE`
 $MD5 $img >$img.md5sum
 echo
-echo "Package complete: $OUTFILE"
-cat $img.md5sum
+echo $CL_GRN"Package complete: $OUTFILE"$CL_RST
+echo $CL_GRN"md5: $(cat $img.md5sum | awk '{ print $1 }')"$CL_RST
 echo
 )
 
